movie_module.movie_config_entity.*:
  type: config_entity
  label: 'Movie Config Entity'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    year:
      type: string
      label: 'Year'
